version: '3'

services:
  webserver:
    build: .
    ports:
    - "80:80"
    tty: true
    environment:
    - DATABASE_HOSTNAME=database
    - DATABASE_PORT=5432

  database:
    image: postgres
    restart: always